name: build

on: workflow_dispatch

jobs:
  run_workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2 
    - name: Display the path
      shell: bash
      run: |
        echo $PATH
    - name: Display the working directory
      shell: bash
      run: |
        echo $PWD
    - name: Display the directory contents
      shell: bash
      run: ls data
    - name: Which Rscript
      shell: bash
      run: |
        chmod +x test.R
        ./test.R
        Rscript --version
        which Rscript
        R --version
    - name: Run Snakemake
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--cores 1 --force --use-conda --conda-cleanup-pkgs cache tester"

