name: build

on: workflow_dispatch

jobs:
  run_workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2 
    - name: Display the path
      shell: bash
      run: |
        echo $PATH \
        echo $PWD \
        ls
    - name: Run Snakemake
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--cores 1 --use-conda --conda-cleanup-pkgs cache"

