name: build

on: workflow_dispatch

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Building
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: '.build'
        snakefile: '/Snakefile'
        args: '--cores 1'
        stagein: 'conda env create -f environment.yml; conda activate drought' # additional preliminary commands to run (can be multiline)
