name: build

on: workflow_dispatch

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Building
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: '.'
        snakefile: 'workflow/Snakefile'
        args: '--cores 1 --use-conda'
        stagein: '' # additional preliminary commands to run (can be multiline)
