name: Run Workflow
run-name: ${{ github.actor }} is running the workflow 🚀

on:
#  push:
  schedule:
    - cron:  '0 17 * * *'


jobs:
  run_workflow:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2 
      
    - name: Display the path
      shell: bash
      run:  echo $PATH
      
    - name: Display the working directory
      shell: bash
      run: echo $PWD
        
    - name: Display the directory contents
      shell: bash
      run: ls data
      
    - name: Which Rscript
      shell: bash
      run: |
        Rscript --version
        which Rscript
        R --version
        
    - name: Run Snakemake
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--cores 1 --force --use-conda --conda-cleanup-pkgs cache visuals/world_drought.png"

    - name: setup git config
      run: |
        git config --local user.email "noreply@github.com"
        git config --local user.name "GitHub"

    - name: commit
      run: |
        # Stage the file, commit and push
        git add visuals/world_drought.png
        git commit -m "New day"
        git push origin main
