name: build

on: workflow_dispatch

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "."

    steps:
      - name: Run Snakemake
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.test'
          snakefile: 'Snakefile'
          args: '--cores 1 --use-conda --conda-cleanup-pkgs cache'

